name: compGatesTest1

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: self-hosted
    steps:
      - name: checking
        run: |
          echo "PR was merged into the main branch!"
          echo "Merge Commit SHA: ${{ github.event.pull_request.merge_commit_sha }}"
